# Generated by Django 3.1.5 on 2021-01-25 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('costo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('abreviado', models.CharField(max_length=2)),
                ('costo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('total', models.FloatField()),
                ('fecha', models.DateField()),
                ('pedido_combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.combo')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descuento', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamano', models.CharField(max_length=20)),
                ('abreviado', models.CharField(max_length=2)),
                ('costo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviado', models.CharField(max_length=2)),
                ('ingrediente_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ingrediente')),
                ('tamano_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tamano')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pedido')),
                ('pizza_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='pedido_promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.promo'),
        ),
    ]
