# Generated by Django 3.1.5 on 2021-01-25 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_pizza',
            name='tamano_pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.tamano'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido_pizza',
            name='pizza_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ingrediente'),
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
