# Generated by Django 3.1.5 on 2021-02-01 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210125_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedido_combo',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pedido_promo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.promo'),
        ),
        migrations.CreateModel(
            name='Pedido_Combo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo_cfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.combo')),
                ('pedido_cfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pedido')),
            ],
        ),
    ]
